### PR TITLE
Remove unused dependency to fix bench build

### LINKED ISSUE #4: benchmark build failure
As seen on the stackage build server (building with ghc-8.2):

```
Building benchmark 'bench' for xxhash-0.0.2..
[1 of 1] Compiling Main             ( bench/Bench.hs, dist/build/bench/bench-tmp/Main.o )

bench/Bench.hs:17:10: error:
    • No instance for (GHC.Generics.Generic M32.Hash32)
        arising from a use of ‘Control.DeepSeq.$dmrnf’
    • In the expression: Control.DeepSeq.$dmrnf @M32.Hash32
      In an equation for ‘rnf’: rnf = Control.DeepSeq.$dmrnf @M32.Hash32
      In the instance declaration for ‘NFData M32.Hash32’
   |
17 | instance NFData M32.Hash32
   |          ^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by brandonhamilton**
Fixes #4 

This would allow `xxhash` to be [unblocked in `stackage nightly`](https://github.com/fpco/stackage/blob/6746407a2615c38cd4bce07cce27132fa5b62291/build-constraints.yaml#L3500), as the package builds correctly with `ghc-8.4.1`.

### CODE REVIEW

**Comment by christian-marie** [comment]
Thank you very much, apologies to all for my long silence, getting back into things now.
